allowBuilds:
  '@firebase/util': set this to true or false
  protobufjs: set this to true or false
  unrs-resolver: set this to true or false
overrides:
  "@firebase/auth": "1.13.3"
  "jwks-rsa>jose": "4.15.9"
